services:
  angular_app:
    build: ./frontend
    container_name: angular_container
    ports:
      - "4200:4200"
    volumes:
      - "./frontend:/frontend"
    tty: true
    stdin_open: true
    command: bash /frontend/angular_start.sh
  go_app:
    build: ./backend
    container_name: go_container
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    volumes:
      - "./backend:/backend"
